### PR TITLE
Update to Babel 7.x

### PR DESCRIPTION
**Pull request by benedyktdryl**
Hi, 

This is my very firs PR which includes Babel 7.x related updates. Please let me know if you will be interested in such contribution so I can make further updates in that matter.

### CODE REVIEW

**Comment by lukeed** [comment]
Hey, very cool. Thanks!

Do you think Babel 7 is stable enough to use in production? I see that it's still `beta` & I know personally that they want more people to test 7 before it's an official release.

I think this is the case, correct me if I'm wrong~! But if so, we should hold off on Babel 7 until it's out of beta. We'll accept this PR when that time comes 😃

**Comment by benedyktdryl** [comment]
Cool - I know it's beta. I made this branch for other guys so they can try to link this version if needed. I will keep eyes on this and go back when it will be more production ready.

**Comment by lukeed** [comment]
Great, thanks!

**Comment by hzlmn** [comment]
@lukeed maybe we can publish it under beta tag? Would like to give it a try and do not want manually fetch from git repo 🐵

**Comment by benedyktdryl** [comment]
I also want to ask for release it under beta tag as it will be easier to test it and also - it would help me a lot to maintain this PR:

https://github.com/zeit/next.js/pull/3428

**Comment by lukeed** [comment]
I'm going to be releasing this as a `next` tag, along with some changes to the Taskr itself under a `next` tag.

I'll come back here shortly when that's prepped!

**Comment by timneutkens** [comment]
@lukeed could you release this as `next`? We're planning to move Next.js to babel 7 soon.

**Comment by lukeed** [comment]
Sure, tbh I forgot about this. I've been messing with Taskr core locally at one point and was hoping it publish it all under the `next` or `beta` tag

**Comment by timneutkens** [comment]
Thanks! Only this would be fine, don't want to fork and release our own version to test 😄

**Comment by timneutkens** [comment]
Just tried it out locally and the PR seems to work well 👍

**Comment by timneutkens** [comment]
@lukeed if you could release it that'd be awesome, it's the only thing holding back the tests in my PR 😄

**Comment by lukeed** [comment]
Do any of the beta deps need to be updated?

**Comment by timneutkens** [comment]
yeah looks like they need to be upgraded to the latest beta, which I believe is `.42`

**Comment by lukeed** [comment]
This is now available as `@taskr/babel@next` 🎉 

I will merge when I'm ready to make the remaining Taskr changes. Thank you all & sorry for the untimely delay(s)~!

**Comment by timneutkens** [comment]
Nice! Thanks Luke 🙏

**Comment by lukeed** [comment]
Moving this into a separate `babel` branch since it's still under a `next` tag release. The request from #315 should also be applied to this (new) branch, moving this `@taskr/babel@next` off the beta version.

Thanks!

**Pull request merged**
